"""Auto-generated strategy: BTCUSDT Funding Rate Momentum.

Hypothesis: Funding rate momentum strategy for BTCUSDT: When funding rates exhibit persistent positive skew (autocorrelation > 0.7 over 24h), enter a delta-neutral carry position scaled by rate magnitude. Exit when autocorrelation drops below 0.3.

Causal mechanism: Perpetual funding mechanism: long-short imbalance → funding rate deviation → arbitrageur entry → mean reversion. The strategy captures the premium during the deviation phase before arbitrageurs force reversion.

Generated by the abundance agentic workflow (Sprint 5-6).
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import polars as pl
from loguru import logger

from abundance.backtesting.metrics import MetricsCalculator, MetricsReport
from abundance.config.settings import settings


def run_strategy(
    pair: str = "BTCUSDT",
    entry_autocorr: float = 0.7,
    exit_autocorr: float = 0.3,
    lookback_periods: int = 72,  # 72 × 8h = 24 days of 8h funding
    position_size_pct: float = 0.02,
) -> tuple[pl.DataFrame, MetricsReport]:
    """Funding rate momentum strategy.

    Entry: funding rate autocorrelation > entry_autocorr over lookback window
    Exit: autocorrelation drops below exit_autocorr
    Position: delta-neutral (short perp + long spot), scaled by rate magnitude.
    """
    pair_lower = pair.lower()

    # Load funding rate data
    funding_path = settings.raw_dir / "funding" / pair_lower
    funding = (
        pl.scan_parquet(str(funding_path / "**" / "*.parquet"))
        .sort("timestamp_ms")
        .collect()
    )

    # Load 1h kline data for spot hedge tracking
    kline_path = settings.raw_dir / "klines" / f"{pair_lower}_1h"
    kline = (
        pl.scan_parquet(str(kline_path / "**" / "*.parquet"))
        .sort("timestamp_ms")
        .collect()
    )

    rates = funding["funding_rate_pct"].to_list()
    timestamps = funding["timestamp_ms"].to_list()

    initial_capital = 10_000.0
    capital = initial_capital
    equity_curve: list[tuple[int, float]] = []
    trades: list[dict] = []
    in_position = False
    position_capital = 0.0
    entry_price = 0.0
    accumulated_funding = 0.0

    for i in range(lookback_periods, len(rates)):
        # Compute rolling autocorrelation
        window = rates[i - lookback_periods : i + 1]
        if len(window) < 2:
            continue

        mean = sum(window) / len(window)
        var = sum((x - mean) ** 2 for x in window) / len(window)
        if var == 0:
            continue

        lagged = window[:-1]
        current = window[1:]
        lagged_mean = sum(lagged) / len(lagged)
        current_mean = sum(current) / len(current)
        cov = sum(
            (lagged[j] - lagged_mean) * (current[j] - current_mean)
            for j in range(len(lagged))
        ) / len(lagged)
        autocorr = cov / var

        rate = rates[i]
        ts = timestamps[i]

        # Get spot price (approximate: closest kline)
        spot_price = kline.filter(
            pl.col("timestamp_ms") <= ts
        )["close"].last()

        # ── Entry ────────────────────────────────────
        if not in_position and autocorr > entry_autocorr:
            position_capital = capital * position_size_pct * abs(rate / 0.01)
            entry_price = spot_price
            accumulated_funding = 0.0
            in_position = True
            continue

        # ── Accumulate funding ───────────────────────
        if in_position:
            accumulated_funding += (rate / 100) * position_capital

        # ── Exit ─────────────────────────────────────
        if in_position and autocorr < exit_autocorr:
            spot_pnl = (entry_price - spot_price) / entry_price * position_capital
            total_pnl = accumulated_funding - spot_pnl
            capital += total_pnl
            trades.append({"pnl": total_pnl, "return_pct": total_pnl / position_capital * 100})
            in_position = False

        # Record equity
        equity_value = capital
        if in_position:
            equity_value = capital + accumulated_funding - (entry_price - spot_price) / entry_price * position_capital
        equity_curve.append((ts, equity_value))

    equity_df = pl.DataFrame(equity_curve, schema=["timestamp_ms", "equity"], orient="row")
    trades_df = pl.DataFrame(trades) if trades else None
    report = MetricsCalculator.from_equity_curve(equity_df, trades_df)
    return equity_df, report
