"""Auto-generated strategy: BTCUSDT Funding Rate Momentum.

Hypothesis: Funding rate momentum strategy for BTCUSDT: When funding rates exhibit persistent positive skew (autocorrelation > 0.7 over 24h), enter a delta-neutral carry position scaled by rate magnitude. Exit when autocorrelation drops below 0.3.

Causal mechanism: Perpetual funding mechanism: long-short imbalance → funding rate deviation → arbitrageur entry → mean reversion. The strategy captures the premium during the deviation phase before arbitrageurs force reversion.

Generated by the abundance agentic workflow (Sprint 5-6).
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import polars as pl
from abundance.backtesting.costs import COST_MODEL
from abundance.backtesting.metrics import MetricsCalculator, MetricsReport
from abundance.config.settings import settings


def run_strategy(
    pair: str = "BTCUSDT",
    position_size_pct: float = 0.05,
) -> tuple[pl.DataFrame, MetricsReport]:
    """Funding rate momentum with cost model and lookahead protection.

    Uses Polars-native rolling correlation (fast, vectorised).
    Position: delta-neutral (short perp + long spot).
    Entry: funding rate > P75 threshold
    Exit: funding rate < P25 threshold
    """
    pair_lower = pair.lower()

    # Load data
    funding = (
        pl.scan_parquet(str(settings.raw_dir / "funding" / pair_lower / "**" / "*.parquet"))
        .sort("timestamp_ms")
        .collect()
    )
    kline = (
        pl.scan_parquet(str(settings.raw_dir / "klines" / f"{pair_lower}_1h" / "**" / "*.parquet"))
        .sort("timestamp_ms")
        .select(["timestamp_ms", "open", "close"])
        .collect()
    )

    rates = funding["funding_rate_pct"]
    timestamps = funding["timestamp_ms"]

    # Dynamic thresholds from data (P75 entry, P25 exit)
    entry_thresh = rates.quantile(0.75)
    exit_thresh = rates.quantile(0.25)
    cost = COST_MODEL

    kline_ts = kline["timestamp_ms"].to_list()
    kline_open = kline["open"].to_list()

    capital = 10_000.0
    equity_curve = [(timestamps[0], capital)]
    trades_list = []
    in_position = False
    pos_capital = 0.0
    pos_entry_price = 0.0
    pos_entry_rate = 0.0
    pos_entry_ts = 0
    total_funding = 0.0

    prev_rate = rates[0]
    for i in range(1, len(rates)):
        ts = timestamps[i]
        current_rate = rates[i]

        # Nearest kline open (no lookahead — use ≤ ts)
        exec_price = kline_open[-1]
        for j in range(len(kline_ts) - 1, -1, -1):
            if kline_ts[j] <= ts:
                exec_price = kline_open[j]
                break

        # Exit check
        if in_position and prev_rate < exit_thresh:
            spot_pnl = (pos_entry_price - exec_price) / pos_entry_price * pos_capital
            gross_pnl = total_funding - spot_pnl
            rt_cost = cost.round_trip_cost(pair, use_perp=True) * pos_capital
            net_pnl = gross_pnl - rt_cost
            capital += net_pnl
            trades_list.append({
                "pnl": net_pnl,
                "return_pct": net_pnl / pos_capital * 100,
            })
            in_position = False

        # Entry check (on previous rate, no lookahead)
        if not in_position and prev_rate > entry_thresh:
            pos_capital = capital * position_size_pct
            pos_entry_price = exec_price
            pos_entry_rate = prev_rate
            pos_entry_ts = ts
            total_funding = 0.0
            in_position = True

        # Accumulate funding
        if in_position:
            total_funding += (current_rate / 100) * pos_capital

        # Equity
        eq = capital
        if in_position:
            spot_delta = (exec_price / pos_entry_price - 1) * pos_capital
            eq = capital + total_funding - spot_delta
        equity_curve.append((ts, eq))

        prev_rate = current_rate

    equity_df = pl.DataFrame(equity_curve, schema=["timestamp_ms", "equity"], orient="row")
    trades_df = pl.DataFrame(trades_list) if trades_list else None
    report = MetricsCalculator.from_equity_curve(equity_df, trades_df)
    return equity_df, report
