"""Generated strategy: RSI Mean Reversion with Cost Model.

Hypothesis: RSI(14) mean reversion captures retail panic selling.
When RSI drops below 30 (oversold), retail traders panic-sell,
creating temporary mispricing that reverts within 1-5 candles.
Entry on oversold signal, exit when RSI returns to neutral (>50).

Causal mechanism: Barber & Odean (2008) disposition effect —
retail investors sell winners too early and hold losers too long.
In crypto, this is amplified by 24/7 markets and leverage cascades.

Generated by the abundance agentic workflow.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import polars as pl

from abundance.backtesting.costs import COST_MODEL
from abundance.backtesting.metrics import MetricsCalculator, MetricsReport
from abundance.config.settings import settings


def run_strategy(
    pair: str = "BTCUSDT",
    rsi_period: int = 14,
    oversold: float = 30.0,
    exit_neutral: float = 50.0,
    position_size_pct: float = 0.10,
) -> tuple[pl.DataFrame, MetricsReport]:
    """RSI mean reversion strategy with full cost accounting.

    Args:
        pair: Trading pair (e.g. 'BTCUSDT').
        rsi_period: RSI lookback period.
        oversold: RSI threshold to enter long.
        exit_neutral: RSI threshold to exit position.
        position_size_pct: Fraction of capital per trade (0.10 = 10%).
    """
    pair_lower = pair.lower()
    cost = COST_MODEL

    # Load 1h kline data
    df = (
        pl.scan_parquet(
            str(settings.raw_dir / "klines" / f"{pair_lower}_1h" / "**" / "*.parquet")
        )
        .sort("timestamp_ms")
        .collect()
    )

    close = df["close"]
    timestamps = df["timestamp_ms"]

    # Compute RSI (Polars-native, vectorised)
    delta = close.diff()
    gain = delta.clip(lower_bound=0)
    loss = (-delta).clip(lower_bound=0)
    avg_gain = gain.rolling_mean(window_size=rsi_period)
    avg_loss = loss.rolling_mean(window_size=rsi_period)
    rs = avg_gain / avg_loss.clip(lower_bound=1e-6)
    rsi = 100.0 - (100.0 / (1.0 + rs))

    # Generate signals with lookahead protection (shift by 1)
    rsi_prev = rsi.shift(1)
    signal_list = []
    rsi_list = rsi_prev.to_list()
    for i in range(len(rsi_list)):
        if rsi_list[i] is None:
            signal_list.append(0.0)
        elif rsi_list[i] < oversold:
            signal_list.append(1.0)
        elif rsi_list[i] > exit_neutral:
            signal_list.append(0.0)
        else:
            signal_list.append(signal_list[-1] if signal_list else 0.0)
    for i in range(min(rsi_period, len(signal_list))):
        signal_list[i] = 0.0

    # Compute strategy returns with costs
    period_ret = close.pct_change().fill_null(0)
    strategy_ret = period_ret * pl.Series(signal_list) * position_size_pct

    # Equity curve
    initial_capital = 10_000.0
    equity_vals = [initial_capital]
    for r in strategy_ret:
        equity_vals.append(equity_vals[-1] * (1 + r))

    equity_curve = pl.DataFrame(
        {
            "timestamp_ms": timestamps,
            "equity": pl.Series(equity_vals[1:]),
        }
    )

    # Build trade log for cost-aware metrics
    sig_series = pl.Series(signal_list)
    sig_changes = sig_series.diff().abs()
    num_trades = int(sig_changes.drop_nulls().sum() / 2)
    round_trip_cost = cost.round_trip_cost(pair)
    gross_pnl = equity_vals[-1] - initial_capital
    net_pnl = gross_pnl - round_trip_cost * initial_capital * num_trades

    trades = []
    if num_trades > 0:
        avg_trade_pnl = net_pnl / num_trades
        trades = [
            {
                "pnl": avg_trade_pnl,
                "return_pct": avg_trade_pnl / (initial_capital * position_size_pct) * 100,
            }
        ] * num_trades

    trades_df = pl.DataFrame(trades) if trades else None
    report = MetricsCalculator.from_equity_curve(equity_curve, trades_df)

    # Net equity after costs
    cost_adjusted = pl.Series(equity_vals[1:]) - round_trip_cost * num_trades * position_size_pct
    report.total_return_pct = (
        (cost_adjusted[-1] / initial_capital - 1) * 100
    )

    return equity_curve, report
