"""Generated strategy: Volatility Breakout with Inverse-Vol Sizing.

Hypothesis: High volatility clusters create directional breakouts.
When price breaks above recent high + 2× ATR, enter long with
position size inversely scaled by current volatility. Exit on
trailing stop at 3× ATR below peak.

Causal mechanism: Mandelbrot (1963) volatility clustering.

Generated by the abundance agentic workflow.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import polars as pl

from abundance.backtesting.costs import COST_MODEL
from abundance.backtesting.metrics import MetricsCalculator, MetricsReport
from abundance.config.settings import settings


def run_strategy(
    pair: str = "BTCUSDT",
    atr_period: int = 14,
    breakout_mult: float = 2.0,
    stop_mult: float = 3.0,
    vol_target: float = 0.20,
) -> tuple[pl.DataFrame, MetricsReport]:
    """Volatility breakout with dynamic position sizing."""
    pair_lower = pair.lower()

    df = (
        pl.scan_parquet(
            str(settings.raw_dir / "klines" / f"{pair_lower}_1h" / "**" / "*.parquet")
        )
        .sort("timestamp_ms")
        .collect()
    )

    close_list = df["close"].to_list()
    high_list = df["high"].to_list()
    low_list = df["low"].to_list()
    timestamps = df["timestamp_ms"].to_list()
    n = len(close_list)

    # ── ATR (pure Python for Polars 1.x compat) ───────────
    atr_list = [0.0] * n
    for i in range(n):
        tr = high_list[i] - low_list[i]
        if i > 0:
            tr = max(tr, abs(high_list[i] - close_list[i-1]), abs(low_list[i] - close_list[i-1]))
        atr_list[i] = tr
    # Rolling mean
    atr_smooth = [0.0] * n
    for i in range(n):
        start = max(0, i - atr_period + 1)
        window = atr_list[start:i+1]
        atr_smooth[i] = sum(window) / len(window)

    # ── Signals ───────────────────────────────────────────
    ret_list = [0.0] + [(close_list[i]/close_list[i-1]-1) for i in range(1, n)]
    base_size = 0.05
    target_vol = vol_target / (365 * 24) ** 0.5

    sig = [0.0] * n
    in_position = False
    peak_price = 0.0

    for i in range(atr_period + 1, n):
        # Position size: inverse volatility
        vol_est = atr_smooth[i-1] / close_list[i-1] if close_list[i-1] > 0 else 0.01
        pos_size = base_size * target_vol / max(vol_est, 0.001)
        pos_size = min(pos_size, 0.20)

        # Rolling max of high (lookback window)
        start_h = max(0, i - atr_period)
        roll_max_high = max(high_list[start_h:i])

        if not in_position:
            # Entry: breakout above recent high + 2× ATR
            if close_list[i] > roll_max_high + breakout_mult * atr_smooth[i-1]:
                sig[i] = pos_size
                in_position = True
                peak_price = close_list[i]
        else:
            # Update peak
            if close_list[i] > peak_price:
                peak_price = close_list[i]
            # Trailing stop
            if close_list[i] < peak_price - stop_mult * atr_smooth[i]:
                sig[i] = 0.0
                in_position = False
            else:
                sig[i] = pos_size

    # ── Equity curve ──────────────────────────────────────
    strategy_ret = [ret_list[i] * sig[i] for i in range(n)]
    initial = 10_000.0
    equity = [initial]
    for r in strategy_ret:
        equity.append(equity[-1] * (1 + r))

    equity_curve = pl.DataFrame(
        {"timestamp_ms": timestamps, "equity": pl.Series(equity[1:])}
    )

    # ── Trades ────────────────────────────────────────────
    num_trades = sum(1 for i in range(1, n) if sig[i] > 0 and sig[i-1] == 0)
    rt_cost = COST_MODEL.round_trip_cost(pair)
    trades = []
    if num_trades > 0:
        avg_pnl = (equity[-1] - initial) / num_trades
        trades = [{"pnl": avg_pnl, "return_pct": avg_pnl / (initial * base_size) * 100}] * num_trades

    trades_df = pl.DataFrame(trades) if trades else None
    report = MetricsCalculator.from_equity_curve(equity_curve, trades_df)
    return equity_curve, report
